### ISSUE TITLE
Fail with error 'nonce must match timestamp index'

### ISSUE THREAD

**Issue by Crypto-Paganism** [tellor-io/telliot-core#163]
When a report is submitted, if someone else has reported a few seconds before then the following error is stated.
https://etherscan.io/tx/0x5377e440361b190081f3324154cbf9641d6511acf21036488882fa2e0736d9af
Rather than rejecting the submission, the report submission is pushed to the next block where the reward is almost 0:
https://etherscan.io/tx/0x864239235c84d1a5c887faa2aa6a57d5f28bd884b556f4924091a679aac59ac5

My pytelliot input was:
telliot-examples -lid 1 report -p -27.336

Im using Virtual Box where I have cloned 3 instances from a single build and changed the private key on each of the 4 instances to run 4 reporters. .

**Comment by Crypto-Paganism** [comment]
Previously today before the above event, the same error was shown, however, the submission was reverted, with only a small gas fee.
https://etherscan.io/tx/0x407331c3bb425bc89c2b8967df45c4a88cdbe70a8ea0cf1585d25f71eddbc17b

**Comment by clamdad** [comment]
The `-p -27.336` flag will actually submit at a 27% loss.  Was that your intention?  Maybe you meant  `-p 27.336` for a 27% profit?

Regarding the submissions, I understand there should be 3 possible outcomes, ranked from best to worst.  The first transaction above seems to be the second case.

- Your submission is the first one mined -> 
  - You win the time-based reward + tips for that query.  Yay!
- Another submission was mined before yours for *the same query* -> 
  - Your submission fails: `Fail with error nonce must match timestamp index`
  - You spend a relatively small amount of ETH on the failed transaction.
- Another submission was mined before yours for *a different query* -> 
  - The other reporter claims the reward+tips
  - Your submission passes (and data is added to the blockchain)
  - You spend the full transaction cost of the data submission.
  - You receive little or no time-based reward because of the previous submission.

I think the second submission might be a bug in the example reporter "retry submission" logic.
Moving this issue to the reporter examples repository.  Please see here for follow-up:
https://github.com/tellor-io/telliot-feed-examples/issues/59

**Comment by Crypto-Paganism** [comment]
Thanks for the comments, 
I used -p -30 as telliot has 500,000 as the gas value in its estimator calculator. The current average gas used is actually around 250,000 therefore the calculator is wrong. A -p -30 function actually results in a +25%ish gain.

**Comment by clamdad** [comment]
Closing this issue as replaced by https://github.com/tellor-io/telliot-feed-examples/issues/59
